# NICK Errors
ERR_NONICKNAMEGIVEN_CODE = '431'
ERR_NONICKNAMEGIVEN_MESSAGE = ':No nickname given'
ERR_ERRONEUSNICKNAME_CODE = '432'
ERR_ERRONEUSNICKNAME_MESSAGE = ':Erroneus nickname'
ERR_NICKNAMEINUSE_CODE = '433'
ERR_NICKNAMEINUSE_MESSAGE = ':Nickname is already in use'
ERR_NICKCOLLISION_CODE = '436'
ERR_NICKCOLLISION_MESSAGE = ':Nickname collision KILL'