# NICK Errors
ERR_NONICKNAMEGIVEN_CODE = '431'
ERR_NONICKNAMEGIVEN_MESSAGE = ':No nickname given'
ERR_ERRONEUSNICKNAME_CODE = '432'
ERR_ERRONEUSNICKNAME_MESSAGE = ':Erroneus nickname'
ERR_NICKNAMEINUSE_CODE = '433'
ERR_NICKNAMEINUSE_MESSAGE = ':Nickname is already in use'
ERR_NICKCOLLISION_CODE = '436'
ERR_NICKCOLLISION_MESSAGE = ':Nickname collision KILL'

# USER Errors
ERR_NEEDMOREPARAMS_CODE = '461'
ERR_NEEDMOREPARAMS_MESSAGE = ':Not enough parameters'
ERR_ALREADYREGISTRED_CODE = '462'
ERR_ALREADYREGISTRED_MESSAGE = ':You may not reregister'

# PRIVMSG Errors
ERR_NOSUCHNICK_CODE = '401'
ERR_NOSUCHNICK_MESSAGE = ':No such nick/channel'
ERR_CANNOTSENDTOCHAN_CODE = '404'
ERR_CANNOTSENDTOCHAN_MESSAGE = ':Cannot send to channel'
